# Generated by Django 5.0.6 on 2024-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("street", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=150)),
                ("postal", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
