# Generated by Django 5.0.6 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_contact_api_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="api_id",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
    ]
