# Generated by Django 5.0.6 on 2024-06-02 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="domain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
