# Generated by Django 5.0.6 on 2024-06-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_domain_created_at_domain_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="pending",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.domain"
                    ),
                ),
            ],
        ),
    ]
